### PR TITLE
add: adding  the docker environment

### PR DESCRIPTION
**Pull request by VisionOra**
Add:
Add the docker file to repo

### CODE REVIEW

**Comment by VisionOra** [comment]
hi @Mindful can you also have a look at this

**Comment by Mindful** [comment]
@SohaibAnwaar thanks for opening a pull request. I won't have time to look at this in detail until this weekend, but I'll try and get back to you then.

**Review by Mindful — CHANGES_REQUESTED** [review]
Hi @SohaibAnwaar,

So I would be happy to merge this PR, it just needs a couple changes. 
1. I think something is weird with the submodules that you added; URL information for them needs to be present in the `.gitmodules` file, but both the file and said info appear to be missing. Consequently, when I try and initialize them with `git submodule init`, it fails like this: `fatal: No url found for submodule path 'training/data/dsbook' in .gitmodules`. Removing these would be fine, but if they're important and you want to keep them please make sure they point to public and officially maintained git repositories. 
2. The docker image appears to be missing a jupyter installation. The command from the readme to start a notebook worked fine for me, but only _after_ I ran `pip install jupyter` inside the docker image, so it would be best to either update the readme instructions to include that or update the docker image so it came with a jupyter install. 
3. I think the docker image is a good addition, we just need to update the readme slightly to clarify that it's not maintained by Octanove. It would be great if you could add an explanation right under the `## Docker Image` header like this:
> SohaibAnwaar has kindly contributed the below docker image to make running the model easier (note this image is not maintained by SHIBA authors). 

Thanks again for opening a PR!

**Comment by Mindful** [comment]
Closing for lack of activity. Please feel free to comment if you'd like to reopen the PR.

**Pull request closed without merging**
